### ISSUE TITLE
Kinect SDK files?

### ISSUE THREAD

**Issue by caseyfarina** [SirLynix/obs-kinect#48] opened 2021-01-12 15:47 UTC
I've been using this last year with a Kinect V2 an it worked great? Thank you!

I recently switched to an Azure Kinect and the kinect source shows up in OBS but is totally blank. Does the entire Azure Kinect SDK need to be copied to the OBS directory?
 I put the folder labeled "Azure Kinect SDK v1.4.1" in the 

obs - bin - 64bit directory and that does not seem to be working. 

Thanks you!

**Comment by SirLynix** [comment] 2021-01-12 15:51
Why did you make a duplicate of #47?

**Comment by caseyfarina** [comment] 2021-01-12 16:00
Sorry for the double post I thought the first one did not post. Feel free to delete this one.

**Closed** 2021-01-12 16:01 UTC
